apiVersion: uds.dev/v1alpha1
kind: MinioManager
metadata:
  name: minio-manager
  namespace: minio
spec:
  secrets:
    - name: something
      fromNamespace: minio
      toNamespace: default
    - name: something-else
      fromNamespace: minio
      toNamespace: default
